---
title: "Untitled"
format: html
---
# Selección de artículo/reporte

- Referencia del artículo seleccionado

Pérez-Ahumada, P., & Carrasco, K. (2025). Política de clases y confianza en los sindicatos en América Latina. Latin American Research Review, 60(2), 410–433. doi:10.1017/lar.2024.64

- Resumen del artículo seleccionado

El artículo investiga los factores individuales y contextuales que explican el nivel de confianza de la ciudadanía en los sindicatos latinoamericanos, para esto se utilizan los datos de la encuesta Latinobarómetro de los años 2018 y 2020. Los autores demuestran que, a nivel individual, la confianza sindical es significativamente mayor entre personas pertenecientes a la clase trabajadora y a la clase media asalariada, así como entre quienes se identifican políticamente con la izquierda y confían más en las instituciones políticas. A nivel contextual, el estudio revela que la legitimidad de los sindicatos varía según el modelo de capitalismo de cada país. La confianza tiende a ser mayor en naciones “neo-desarrollistas” (como Brasil y Uruguay) y más baja en países de “capitalismo tercerizado” (como México y Centroamérica). También encontraron que la confianza en los sindicatos en Chile es alta, siendo un país liberal-rentista con sindicatos débiles, y baja en países redistributivos-rentistas y desarrollistas. Finalmente, los investigadores analizan cómo la confianza en los sindicatos depende de variables contextuales como la informalidad laboral, la inflación, el nivel de desempleo y las movilizaciones sociales.


- Justificación de la selección del artículo
La elección de este artículo se fundamenta por tres motivos principales: su relevancia regional, su aporte teórico e interdisciplinario, y su potencial para el ejercicio de reproducibilidad. En relación a su relevancia regional, este artículo aborda una temática clave para comprender la cohesión social y las dinámicas de la política laboral en América Latina, ya que al analizar cómo los diferentes modelos económicos impactan en la sociedad, permite enriquecer el debate y generar evidencia sobre la percepción que se tiene de las organizaciones de los trabajadores en la región. En segundo lugar, el texto propone una articulación analítica entre las clases sociales, los tipos de capitalismo y la legitimidad social de los sindicatos. Por último, el artículo resulta especialmente adecuado para este ejercicio porque los autores declaran haber liberado sus datos y códigos en un repositorio público, lo que en principio facilita la posibilidad de replicar los análisis y verificar sus resultados.

