# Conclusiones

En síntesis, si bien el artículo cumple con distintos criterios que permiten la reproducibilidad (como la disponibilidad de datos y códigos, y la descripción de las hipótesis, variables, métodos y procedimientos), esta resulta limitada. El proceso de reproducción se dificultó por distintas razones: en primer lugar, por la falta del código de limpieza de los datos, por lo cual se debió intentar reconstruir a partir de la información del estudio; en segundo lugar, por la operacionalización compleja de ciertas variables como la clase social, la cual debía hacerse bajo el esquema de Wright; y por último, por la falta de información sobre decisiones metodológicas como el tratamiento de casos perdidos. 

En consecuencia, no se pudieron replicar con exactitud las figuras, ya que no se pudo alcanzar la representatividad de la muestra, la cual quedó en 22.384 casos, en comparación con las 25.286 observaciones reportadas. Esta reducción de la muestra afectó también en la reproducción de los gráficos, los cuales difieren a los publicados, debido a que el intercepto es menor, por lo que cae el cálculo del porcentaje de probabilidad, dando resultados diferentes a los establecidos por la investigación. Por estos motivos, se concluye que el nivel de reproducibilidad del artículo seleccionado es restringido, y queda evidenciada la necesidad de una documentación más exhaustiva de las herramientas utilizadas por este. 
